import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar GENERADO por scripts/migrate-docs.py desde el `docs.json` del
 * repo del lenguaje.
 *
 * La arquitectura de información es una decisión editorial que el autor ya
 * tomó en el corpus. Reordenarla aquí a mano crearía una segunda verdad que
 * se desincronizaría en la primera página nueva.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'index',
        'quickstart',
        'install',
      ],
    },
    {
      type: 'category',
      label: 'The idea',
      collapsed: true,
      items: [
        'concepts/compile-time-compliance',
        'concepts/epistemic-types',
      ],
    },
    {
      type: 'category',
      label: 'Examples · Agents',
      collapsed: true,
      items: [
        'examples/agent_react',
        'examples/reflex_to_immune',
      ],
    },
    {
      type: 'category',
      label: 'Examples · Composition',
      collapsed: true,
      items: [
        'examples/flow_chaining',
        'examples/flow_step_basic',
        'examples/grad_proof_carrying',
        'examples/module_imports',
        'examples/quant_feature_map',
        'examples/temporal_cognitive_context',
        'examples/tool_structured_args',
        'examples/tool_use_basic',
        'examples/weave_braid',
      ],
    },
    {
      type: 'category',
      label: 'Examples · Data',
      collapsed: true,
      items: [
        'examples/axonstore_typed',
        'examples/dataspace_basic',
        'examples/governed_crm_delivery',
        'examples/governed_data_pipeline',
        'examples/governed_notification',
        'examples/secret_custody_rotation',
        'examples/secret_partition_multitenant',
      ],
    },
    {
      type: 'category',
      label: 'Examples · Effects',
      collapsed: true,
      items: [
        'examples/lambda_epistemic_stamp',
      ],
    },
    {
      type: 'category',
      label: 'Examples · Endpoints',
      collapsed: true,
      items: [
        'examples/axonendpoint_rest',
        'examples/cors_named_origin_policy',
        'examples/query_safe_search',
        'examples/widget_ephemeral_credential',
      ],
    },
    {
      type: 'category',
      label: 'Examples · Memory',
      collapsed: true,
      items: [
        'examples/memory_scopes',
      ],
    },
    {
      type: 'category',
      label: 'Examples · Session Types',
      collapsed: true,
      items: [
        'examples/session_chat_duality',
        'examples/socket_websocket_chat',
      ],
    },
    {
      type: 'category',
      label: 'Examples · Shields',
      collapsed: true,
      items: [
        'examples/shield_input_output',
      ],
    },
    {
      type: 'category',
      label: 'Examples · Streaming',
      collapsed: true,
      items: [
        'examples/streaming_chat',
      ],
    },
    {
      type: 'category',
      label: 'Examples · Validation',
      collapsed: true,
      items: [
        'examples/anchor_validation',
        'examples/mandate_policy',
      ],
    },
    {
      type: 'category',
      label: 'Doctrines',
      collapsed: true,
      items: [
        'doctrines/a_derivative_is_derived_not_sampled',
        'doctrines/a_safe_method_is_proven_safe',
        'doctrines/analysis_is_algebra_not_conversation',
        'doctrines/attention_is_a_governed_resource',
        'doctrines/authority_only_attenuates',
        'doctrines/connections_release_across_cognition',
        'doctrines/delivery_is_a_kept_promise',
        'doctrines/delivery_is_assertion_egress',
        'doctrines/dispatch_vs_cognition',
        'doctrines/effect_execution_is_mode_invariant',
        'doctrines/effects_are_linear',
        'doctrines/every_boundary_is_guarded',
        'doctrines/every_granted_authority_projects',
        'doctrines/every_requirement_is_grantable',
        'doctrines/flow_composition',
        'doctrines/no_unwitnessed_advantage',
        'doctrines/open_data_is_total',
        'doctrines/rotation_without_revelation',
        'doctrines/selection_without_revelation',
        'doctrines/session_duality',
        'doctrines/time_is_an_explicit_input',
        'doctrines/total_expressions',
      ],
    },
    {
      type: 'category',
      label: 'Grammar',
      collapsed: true,
      items: [
        'grammar/composition',
        'grammar/ebnf',
        'grammar/top_level',
      ],
    },
    {
      type: 'category',
      label: 'Compliance',
      collapsed: true,
      items: [
        'compliance/regulatory-classes',
        'compliance/fedramp',
        'compliance/fisma',
        'compliance/gdpr',
        'compliance/gxp',
        'compliance/hipaa',
        'compliance/nist_800_53',
        'compliance/pci_dss',
        'compliance/soc2',
        'compliance/sox',
      ],
    },
    {
      type: 'category',
      label: 'Templates',
      collapsed: true,
      items: [
        'templates/banking',
        'templates/business_intelligence',
        'templates/chat',
        'templates/chat_research',
        'templates/chat_skills',
        'templates/chat_tools',
        'templates/compliance_monitoring',
        'templates/content_moderation',
        'templates/corporate_integration',
        'templates/data_pipeline',
        'templates/dev',
        'templates/document_analysis',
        'templates/education',
        'templates/financial_advisor',
        'templates/fintech',
        'templates/generic',
        'templates/government',
        'templates/healthcare',
        'templates/knowledge_extraction',
        'templates/legal',
        'templates/legaltech',
        'templates/medic_research',
        'templates/multi_agent',
        'templates/pharmatech',
        'templates/recruitment',
        'templates/retrieval',
        'templates/sales_consultive',
        'templates/sales_widget',
        'templates/self_learning',
        'templates/ticket_triage',
        'templates/voice',
        'templates/voice_preset',
        'templates/whatsapp',
        'templates/workflow_automation',
      ],
    },
    {
      type: 'category',
      label: 'Reference · Cognition',
      collapsed: true,
      items: [
        'reference/primitives/agent',
        'reference/primitives/anchor',
        'reference/primitives/believe',
        'reference/primitives/consensus',
        'reference/primitives/context',
        'reference/primitives/deliberate',
        'reference/primitives/doubt',
        'reference/primitives/flow',
        'reference/primitives/hibernate',
        'reference/primitives/intent',
        'reference/primitives/know',
        'reference/primitives/memory',
        'reference/primitives/par',
        'reference/primitives/persona',
        'reference/primitives/probe',
        'reference/primitives/reason',
        'reference/primitives/refine',
        'reference/primitives/run',
        'reference/primitives/speculate',
        'reference/primitives/step',
        'reference/primitives/tool',
        'reference/primitives/validate',
        'reference/primitives/weave',
      ],
    },
    {
      type: 'category',
      label: 'Reference · Operators',
      collapsed: true,
      items: [
        'reference/primitives/budget',
        'reference/primitives/cache',
        'reference/primitives/compute',
        'reference/primitives/cors',
        'reference/primitives/credential',
        'reference/primitives/deliver',
        'reference/primitives/document',
        'reference/primitives/effect',
        'reference/primitives/extension',
        'reference/primitives/forge',
        'reference/primitives/grad',
        'reference/primitives/handle',
        'reference/primitives/lambda',
        'reference/primitives/mandate',
        'reference/primitives/notify',
        'reference/primitives/observable',
        'reference/primitives/ots',
        'reference/primitives/perform',
        'reference/primitives/psyche',
        'reference/primitives/quant',
        'reference/primitives/savant',
        'reference/primitives/scope',
        'reference/primitives/shield',
        'reference/primitives/stream',
        'reference/primitives/synth',
        'reference/primitives/warden',
        'reference/primitives/window',
        'reference/primitives/witness',
      ],
    },
    {
      type: 'category',
      label: 'Reference · Data plane',
      collapsed: true,
      items: [
        'reference/primitives/aggregate',
        'reference/primitives/associate',
        'reference/primitives/axonstore',
        'reference/primitives/corpus',
        'reference/primitives/dataspace',
        'reference/primitives/drill',
        'reference/primitives/explore',
        'reference/primitives/focus',
        'reference/primitives/ingest',
        'reference/primitives/json',
        'reference/primitives/ledger',
        'reference/primitives/navigate',
        'reference/primitives/pix',
        'reference/primitives/trail',
        'reference/primitives/type',
      ],
    },
    {
      type: 'category',
      label: 'Reference · Wire',
      collapsed: true,
      items: [
        'reference/primitives/axonendpoint',
        'reference/primitives/axpoint',
        'reference/primitives/channel',
        'reference/primitives/component',
        'reference/primitives/daemon',
        'reference/primitives/discover',
        'reference/primitives/emit',
        'reference/primitives/listen',
        'reference/primitives/mcp',
        'reference/primitives/mint',
        'reference/primitives/publish',
        'reference/primitives/rotate',
        'reference/primitives/view',
      ],
    },
    {
      type: 'category',
      label: 'Reference · Cognitive I/O',
      collapsed: true,
      items: [
        'reference/primitives/compliance',
        'reference/primitives/ensemble',
        'reference/primitives/fabric',
        'reference/primitives/heal',
        'reference/primitives/immune',
        'reference/primitives/lease',
        'reference/primitives/manifest',
        'reference/primitives/observe',
        'reference/primitives/reconcile',
        'reference/primitives/reflex',
        'reference/primitives/resource',
      ],
    },
    {
      type: 'category',
      label: 'Reference · Session types',
      collapsed: true,
      items: [
        'reference/primitives/branch',
        'reference/primitives/receive',
        'reference/primitives/select',
        'reference/primitives/send',
        'reference/primitives/session',
        'reference/primitives/socket',
        'reference/primitives/topology',
        'reference/primitives/upstream',
        'reference/primitives/voice',
      ],
    },
  ],
};

export default sidebars;
